const filterTagButtons = [
  // 'accountants',
  "thistles",
  // 'clams',
  // 'accordion',
  // 'movie poster',
  "art deco",
  "art nouveau",
  "bauhaus",
  "bouquets",
  "cubism",
  "gradient",
  "mid-century modern",
  "modern",
  "modernism",
  "op art",
  "palm trees",
  "pattern",
  "postmodern",
  "sidewall",
  "textile",
  "textile design",
  "wall decoration",
  "wallpaper",
];

export default filterTagButtons;
